AWSTemplateFormatVersion: '2010-09-09'

Description: Creating IAM resources

Parameters:
  IamNameTag:
    Description: This name will be only in iam resources
    Type: String
    Default: first

Transform: AWS::LanguageExtensions

Resources:
  thisIamGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Join
        - ''
        - - my
          - !Ref IamNameTag
          - Group
      Path: /

  Fn::ForEach::iamUsersToGroup:
    - userName
    - - userOne
      - userTwo
      - userThree
    - thisIam${userName}:
        Type: AWS::IAM::User
        Properties:
          UserName: !Ref userName
          Groups:
            - !Ref thisIamGroup
          LoginProfile:
            Password: b98*uU723465
            PasswordResetRequired: true
          ManagedPolicyArns:
            - arn:aws:iam::aws:policy/IAMUserChangePassword
          Tags:
            - Key: Name
              Value: !Join
                - ''
                - -  !Ref IamNameTag
                  -  !Ref userName

Outputs:
  currentAccount:
    Description: The ID of the AWS account
    Value: !Ref AWS::AccountId
  currentRegion:
    Description: The region of the stack and their resources
    Value: !Ref AWS::Region
  currentStack:
    Description: The region of the stack and their resources
    Value: !Ref AWS::StackName
  iamGroupArn:
    Description: The user group ARN
    Value: !GetAtt thisIamGroup.Arn
    Export:
      Name: !Join
        - ''
        - -  !Ref AWS::StackName
          -  iamGroupArn
  username1:
    Description: The user 1 ARN
    Value: !GetAtt thisIamuserOne.Arn
    Export:
      Name: !Join
        - ''
        - -  !Ref AWS::StackName
          -  thisIamuserOne
  username2:
    Description: The user 2 ARN
    Value: !GetAtt thisIamuserTwo.Arn
    Export:
      Name: !Join
        - ''
        - -  !Ref AWS::StackName
          -  thisIamuserTwo
  username3:
    Description: The user 3 ARN
    Value: !GetAtt thisIamuserThree.Arn
    Export:
      Name: !Join
        - ''
        - -  !Ref AWS::StackName
          -  thisIamuserThree
