AWSTemplateFormatVersion: '2010-09-09'

Description: Creating just VPC resources

Parameters:
  VpcTag:
    Description: This name will be only in the vpc resources
    Type: String
    Default: module-vpc
  VpcCidr:
    Description: This name will be only in the vpc resources
    Type: String
    Default: 10.0.0.0/16

Resources:
  thisVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      Tags:
        - Key: Name
          Value: !Ref VpcTag

  thisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref thisVpc
      GroupDescription: created with cf
      GroupName: !Ref VpcTag
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Enable all of the traffic
          FromPort: 0
          ToPort: 0
          IpProtocol: -1
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          Description: Inbound to ssh
          FromPort: 22
          ToPort: 22
          IpProtocol: TCP
      Tags:
        - Key: Name
          Value: !Ref VpcTag

Outputs:
  currentAccount:
    Description: The ID of the AWS account
    Value: !Ref AWS::AccountId
  currentRegion:
    Description: The region of the stack and their resources
    Value: !Ref AWS::Region
  currentStack:
    Description: The region of the stack and their resources
    Value: !Ref AWS::StackName

  vpcCidr:
    Description: The cidr of the VPC
    Value: !GetAtt thisVpc.CidrBlock
    Export:
      Name: !Join
        - ''
        - -  !Ref AWS::StackName
          -  VpcCidr
  vpcDefaultSecurityGroup:
    Description: The default security group of the VPC
    Value: !GetAtt thisVpc.DefaultSecurityGroup
    Export:
      Name: !Join
        - ''
        - -  !Ref AWS::StackName
          -  vpcDefaultSecurityGroup
  vpcId:
    Description: The vpc ID
    Value: !Ref thisVpc
    Export:
      Name: !Join
        - ''
        - -  !Ref AWS::StackName
          -  vpcId
  vpcSgpId:
    Description: The ID of the security group
    Value: !GetAtt thisSecurityGroup.GroupId
    Export:
      Name: !Join
        - ''
        - -  !Ref AWS::StackName
          -  vpcSgpId
